[build]
  base = "."
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18.18.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
